name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: arduino/setup-protoc@v3
      - name: Generate protos
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
          mkdir -p pkg/ingestion_proto
          protoc --proto_path ./proto \
            --go_out=./pkg/ingestion_proto \
            --go_opt=paths=source_relative \
            --go-grpc_out=./pkg/ingestion_proto \
            --go-grpc_opt=paths=source_relative \
            ./proto/ingestion.proto \
            ./proto/event.proto
      - name: Build
        run: |
          go build -o hotspot-ingestion
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hotspot-ingestion
          path: hotspot-ingestion
