name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Get Protoc
        run: |
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Generate protos
        run: |
          protoc --proto_path ./proto \
            --go_out=./pkg/ingestion_proto \
            --go_opt=paths=source_relative \
            --go-grpc_out=./pkg/ingestion_proto \
            --go-grpc_opt=paths=source_relative
            ./proto/*.proto
      - name: Build
        run: |
          go build -o hotspot-ingestion
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hotspot-ingestion
          path: hotspot-ingestion
