name: Build and publish a Docker image to ghcr.io
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [published]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Build and publish Docker image
        uses: macbre/push-to-ghcr@v15
        with:
          image_name: ${{ github.repository }} # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
